### ISSUE TITLE
Presplit fail

### ISSUE THREAD

**Issue by pulquero** [Merck/Halyard#49]
When I run
$ ~/halyard-2.1/halyard presplit -s /testData/rdf/ -t halyard:mydata -o -g hdfs://....../testdata/ &
i get the following error on reduce:

Error: java.io.IOException: Unable to move table from temp=hdfs://......../hbase-halyard/.tmp/data/halyard/mydata to hbase root=hdfs://........./hbase-halyard/data/halyard/mydata
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:95)
        at org.apache.hadoop.hbase.util.ForeignExceptionUtil.toIOException(ForeignExceptionUtil.java:45)
        at org.apache.hadoop.hbase.client.HBaseAdmin$ProcedureFuture.convertResult(HBaseAdmin.java:4621)
        at org.apache.hadoop.hbase.client.HBaseAdmin$ProcedureFuture.waitProcedureResult(HBaseAdmin.java:4579)
        at org.apache.hadoop.hbase.client.HBaseAdmin$ProcedureFuture.get(HBaseAdmin.java:4512)
        at org.apache.hadoop.hbase.client.HBaseAdmin.createTable(HBaseAdmin.java:677)
        at com.msd.gin.halyard.common.HalyardTableUtils.getTable(HalyardTableUtils.java:166)
        at com.msd.gin.halyard.tools.HalyardPreSplit$PreSplitReducer.cleanup(HalyardPreSplit.java:130)
        at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:179)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.IOException): UUnable to move table from temp=hdfs://......../hbase-halyard/.tmp/data/halyard/mydata to hbase root=hdfs://........./hbase-halyard/data/halyard/mydata
        at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.createFsLayout(CreateTableProcedure.java:388)
        at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.createFsLayout(CreateTableProcedure.java:352)
        at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:118)
        at org.apache.hadoop.hbase.master.procedure.CreateTableProcedure.executeFromState(CreateTableProcedure.java:58)
        at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:119)
        at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:498)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1147)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:942)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:895)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$400(ProcedureExecutor.java:77)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$2.run(ProcedureExecutor.java:497)

In HDFS, /hbase-halyard/.tmp/data/halyard is an empty directory, no mydata files or directory.

**Comment by pulquero** [comment]
It works if I use the default table namespace, i.e. "-t mydata".

**Comment by asotona** [comment]
There are several potential reasons of such issue. 
The target HBase namespace does not exist, or actual user does not have rights to it, or there is another HBase-to-filesystem access rights configuration issue.
To verify the real root cause you can use hbase shell and try to create the namespace and then create any empty table in that namespace following way:
> hbase shell
hbase> create_namespace "halyard"
hbase> create "halyard:test", "test_cf"
hbase> disable "halyard:test"
hbase> drop "halyard:test"

If the above test works for you, then try to run the presplit again and let me know.

Thanks for the report,
Adam
